# Generated by Django 5.0.2 on 2024-05-08 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
